# Generated by Django 3.1.7 on 2022-02-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_image', models.ImageField(blank=True, null=True, upload_to='fish_image')),
                ('fish_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fish_species', models.CharField(blank=True, max_length=200, null=True)),
                ('fish_weight', models.FloatField(blank=True, default=None, null=True)),
                ('fish_length', models.FloatField(blank=True, default=None, null=True)),
                ('fish_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('fish_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
