# Generated by Django 3.1.7 on 2022-02-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220206_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishdetail',
            name='uploaded_by',
        ),
    ]
