# Generated by Django 3.1.7 on 2022-02-06 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_fishdetail_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetail',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
